@URL_BASE=http://localhost:8080

@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImRvdWdsYXMubWFyY29uZGVzQGdtYWlsLmNvbSIsImlhdCI6MTcwMTg3OTMyMiwiZXhwIjoxNzAxODgyOTIyLCJpc3MiOiJVVEZQUiJ9.bTr3Nz7id9pMakqzYiI3F1OLwVKI3DzZrw8zILKuCcM


###Obter todos os pacotes
GET {{URL_BASE}}/auth
Authorization: Bearer {{TOKEN}}

### Cadastrar 1 usuário
POST {{URL_BASE}}/auth
Content-Type: application/json

{
    "username" : "douglas.marcondes@gmail.com",
    "password" : "resende123"
}

