@URL_BASE=http://localhost:8080

###Obter todos os pacotes
GET {{URL_BASE}}/pacote

###Obter todos os pacotes por pagina
GET {{URL_BASE}}/pacote/pages?size=20&page=0&sort=id&direction=DESC

###Obter uma pacote
GET {{URL_BASE}}/pacote/42c571c6-41d6-4f5e-9f4a-96600512d3f1

### Cadastrar 1 pacote
POST {{URL_BASE}}/pacote
Content-Type: application/json

{
    "passeio" : {"id" : "a9390495-5741-4404-9814-5f86b411a5e3"}
}

### Atualizar 1 pacote
PUT {{URL_BASE}}/pacote/b467bf79-4aad-485d-99dd-7ec2ee94a565
Content-Type: application/json

{
    "passeio" : { "id" : "520db4b2-f810-4692-9ac6-a1375065b7fd"},
    "passeio" : { "id" : "1c34a478-bea7-435e-8905-3179231f123e"}
}

### Deletar 1 pacote
DELETE {{URL_BASE}}/pacote/42c571c6-41d6-4f5e-9f4a-96600512d3f1

{

}