@URL_BASE=http://localhost:8080
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImRvdWdsYXMubWFyY29uZGVzQGdtYWlsLmNvbSIsImlhdCI6MTcwMTg3OTMyMiwiZXhwIjoxNzAxODgyOTIyLCJpc3MiOiJVVEZQUiJ9.bTr3Nz7id9pMakqzYiI3F1OLwVKI3DzZrw8zILKuCcM

###Obter todos os pacotes
GET {{URL_BASE}}/pacote
Authorization: Bearer {{TOKEN}}


###Obter todos os pacotes por pagina
GET {{URL_BASE}}/pacote/pages?size=20&page=0&sort=id&direction=DESC
Authorization: Bearer {{TOKEN}}


###Obter uma pacote
GET {{URL_BASE}}/pacote/547896d3-ec00-4898-bc24-9e44945894bb
Authorization: Bearer {{TOKEN}}


### Cadastrar 1 pacote
POST {{URL_BASE}}/pacote
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome" : "Teste",
    "preco"    : 1000.00,
    "passeios" : [
        { "id" : "c7ea3c08-d06e-48b3-a0a7-7ac7ce777087" },
        { "id" : "4a2df9f7-aa41-4edd-80b8-09432896c631" }
    ]
}

### Atualizar 1 pacote
PUT {{URL_BASE}}/pacote/977708cb-d299-4492-90d8-35db9a8277a5
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome" : "8 ou 80 RJ",
    "passeios" : [ 
        { "id" : "72fdb723-4647-480d-bb80-c1abcc03a3b0" },
        { "id" : "c43d25d6-1be3-41fd-b5fb-e96977c151d5" }
    ]
}

### Deletar 1 pacote
DELETE {{URL_BASE}}/pacote/42c571c6-41d6-4f5e-9f4a-96600512d3f1
Authorization: Bearer {{TOKEN}}

{

}