@URL_BASE=http://localhost:8080

@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImRvdWdsYXMubWFyY29uZGVzQGdtYWlsLmNvbSIsImlhdCI6MTcwMjMxMzUzNiwiZXhwIjoxNzAyMzE3MTM2LCJpc3MiOiJVVEZQUiJ9.izhOYgFJVBEXcfqhgvABiExjoFVvuAqI2E6cNBXsQ8k


###Obter todas as pessoas
GET {{URL_BASE}}/pessoa
Authorization: Bearer {{TOKEN}}

###Obter todas as pessoas por pagina
GET {{URL_BASE}}/pessoa/pages?size=20&page=0&sort=email&direction=DESC
Authorization: Bearer {{TOKEN}}

###Obter uma pessoa
GET {{URL_BASE}}/pessoa/1b699bd6-f2af-41ab-8bdf-22d00b0c1fe0


### Cadastrar 1 pessoa
POST {{URL_BASE}}/pessoa
Content-Type: application/json

{
    "nome": "Douglas Marcondes",
    "email": "douglas.marcondes@gmail.com",
    "telefone": "+5545998217562",
    "aniversario": "1995-04-17",
    "identificacao": "Administrador",
    "senha": "resende123"
}

### Atualizar 1 pessoa
PUT {{URL_BASE}}/pessoa/9c594d7b-8047-46cc-b4dd-395cc9e6f304
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Douglas Marcondes",
    "email": "douglas.marcondes@gmail.com",
    "telefone": "+5545998217562",
    "aniversario": "1991-03-04",
    "identificacao": "Administrador",
    "senha": "resende123"
}



### Deletar 1 pessoa
DELETE {{URL_BASE}}/pessoa/1b699bd6-f2af-41ab-8bdf-22d00b0c1fe0

{

}